// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vkrfepzlvjiwumtfhyyp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZrcmZlcHpsdmppd3VtdGZoeXlwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwNzcxOTIsImV4cCI6MjA2NzY1MzE5Mn0.pzGv0SITg_tj6UjARCglzuT7etsnjSwlFNz_x1NqxR8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});